### ISSUE TITLE
How to remap mouse scroll down to mouse scroll up?

### ISSUE THREAD

**Issue by helperman** [igorofc/mouse-and-video#2]
I want to scroll down to make go forward and scroll up to go backward.
Is it possible to set up?

**Comment by igorofc** [comment]
Are you testing the extension? You need to change '<' to '>' after the variable 'movimento' in the mudaTempo() function.

**Comment by helperman** [comment]
I found another solution, way easier.
Just set negative values here:

![00000276](https://user-images.githubusercontent.com/8351863/85590525-27853600-b64d-11ea-8227-4c7c2a2fe8aa.png)
